# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
commonLabels:
  cluster.x-k8s.io/v1beta1: v1beta1
resources:
- bases/infrastructure.cluster.x-k8s.io_equinixmetalclusters.yaml
- bases/infrastructure.cluster.x-k8s.io_equinixmetalmachines.yaml
- bases/infrastructure.cluster.x-k8s.io_equinixmetalmachinetemplates.yaml
#+kubebuilder:scaffold:crdkustomizeresource

patchesStrategicMerge:
- patches/webhook_in_equinixmetalclusters.yaml
- patches/webhook_in_equinixmetalmachines.yaml
- patches/webhook_in_equinixmetalmachinetemplates.yaml
#+kubebuilder:scaffold:crdkustomizewebhookpatch

- patches/cainjection_in_equinixmetalclusters.yaml
- patches/cainjection_in_equinixmetalmachines.yaml
- patches/cainjection_in_equinixmetalmachinetemplates.yaml
#+kubebuilder:scaffold:crdkustomizecainjectionpatch

# the following config is for teaching kustomize how to do kustomization for CRDs.
configurations:
- kustomizeconfig.yaml
